# Generated by Django 5.2.5 on 2025-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vegetarienne', models.BooleanField(default=False)),
            ],
        ),
    ]
